const express=require("express"),Product=require("../models/Product"),{auth,admin}=require("../middleware/auth");
const {connected}=require("../config/database");
const demo=require("../demoStore");
const r=express.Router();
function demoList(req){let items=[...demo.all()];const s=(req.query.search||"").trim().toLowerCase();if(s)items=items.filter(p=>`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(s));if(req.query.category)items=items.filter(p=>p.category===req.query.category);if(req.query.maxPrice)items=items.filter(p=>p.price<=Number(req.query.maxPrice));if(req.query.sort==="price_asc")items.sort((a,b)=>a.price-b.price);else if(req.query.sort==="price_desc")items.sort((a,b)=>b.price-a.price);else items.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return items.slice(0,Math.min(Number(req.query.limit)||50,100));}
r.get("/",async(req,res)=>{try{if(!connected())return res.json({products:demoList(req),demo:true});let q={};if(req.query.search)q.$or=[{name:{$regex:req.query.search,$options:"i"}},{category:{$regex:req.query.search,$options:"i"}}];if(req.query.category)q.category=req.query.category;if(req.query.maxPrice)q.price={$lte:Number(req.query.maxPrice)};let sort=req.query.sort==="price_asc"?{price:1}:req.query.sort==="price_desc"?{price:-1}:{createdAt:-1};let products=await Product.find(q).sort(sort).limit(Math.min(Number(req.query.limit)||50,100));res.json({products});}catch(e){console.error("GET /api/products failed:",e);res.status(500).json({message:"Unable to load products"});}});
r.get("/:id",async(req,res)=>{try{if(!connected()){const p=demo.get(req.params.id);return p?res.json(p):res.status(404).json({message:"Product not found"});}let p=await Product.findById(req.params.id);if(!p)return res.status(404).json({message:"Product not found"});res.json(p)}catch{res.status(404).json({message:"Product not found"})}});
r.post("/",auth,admin,async(req,res)=>{if(!connected())return res.status(201).json(demo.add(req.body));res.status(201).json(await Product.create(req.body))});
r.delete("/:id",auth,admin,async(req,res)=>{if(!connected()){return demo.remove(req.params.id)?res.json({message:"Deleted"}):res.status(404).json({message:"Product not found"})}await Product.findByIdAndDelete(req.params.id);res.json({message:"Deleted"})});
module.exports=r;
