require("dotenv").config();const express=require("express"),cors=require("cors"),path=require("path"),bcrypt=require("bcryptjs");const {connectDB}=require("./config/database");const User=require("./models/User"),Product=require("./models/Product");const auth=require("./routes/auth"),products=require("./routes/products"),wishlist=require("./routes/wishlist"),orders=require("./routes/orders"),admin=require("./routes/admin"),payments=require("./routes/payments");const app=express();app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,"..","frontend")));app.use("/api/auth",auth);app.use("/api/products",products);app.use("/api/wishlist",wishlist);app.use("/api/orders",orders);app.use("/api/admin",admin);app.use("/api/payments",payments);app.get("/api/health",(req,res)=>res.json({ok:true}));
app.use((req,res,next)=>{if(req.path.startsWith("/api/"))return next();res.sendFile(path.join(__dirname,"..","frontend","index.html"));});const demoProducts=[
["Floral Embroidered Blouse","Embroidered Blouses",1299,"https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=700&q=80"],
["Elegant Black Designer Blouse","Designer Blouses",1799,"https://images.unsplash.com/photo-1564257577054-0d6a4f7b0d5c?auto=format&fit=crop&w=700&q=80"],
["Pink Casual Blouse","Casual Blouses",699,"https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=700&q=80"],
["Classic Saree Blouse","Saree Blouses",1499,"https://images.unsplash.com/photo-1585488431767-1b2e1f7a1a9f?auto=format&fit=crop&w=700&q=80"],
["Red Party Wear Blouse","Party Wear Blouses",1999,"https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=80"],
["White Premium Blouse","Premium Blouses",1599,"https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=80"],
["Green Designer Blouse","Designer Blouses",1399,"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=700&q=80"],
["Festive Embroidered Blouse","Embroidered Blouses",1899,"https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=700&q=80"]
];
async function seed(){if(!process.env.MONGODB_URI)return;let adminEmail=process.env.ADMIN_EMAIL||"admin@glowwear.local";if(!await User.findOne({email:adminEmail}))await User.create({name:"GlowWear Admin",email:adminEmail,password:await bcrypt.hash(process.env.ADMIN_PASSWORD||"Admin@12345",10),role:"admin"});if(await Product.countDocuments()===0)await Product.insertMany(demoProducts.map(x=>({name:x[0],category:x[1],price:x[2],image:x[3],stock:50,description:"A curated GlowWear fashion piece designed for modern everyday style."})))}async function start(){await connectDB();await seed();const port=Number(process.env.PORT)||5050;const httpServer=app.listen(port,()=>console.log(`GlowWear running at http://localhost:${port}`));httpServer.on("error",err=>{console.error(err);process.exit(1)});}start().catch(e=>{console.error(e);process.exit(1)});