function header(){const u=user();document.getElementById("siteHeader").innerHTML=`<div class="header"><a class="logo" href="index.html">GlowWear</a><nav class="nav"><a href="shop.html">Shop</a><a href="shop.html?category=Designer%20Blouses">Designer Blouses</a><a href="shop.html?category=Saree%20Blouses">Saree Blouses</a><a href="shop.html?category=Party%20Wear%20Blouses">Party Wear</a></nav><div class="actions"><a href="wishlist.html">♡ <span>Wishlist</span></a><a href="cart.html">🛒 <span id="cartCount">0</span></a>${u?`<a href="orders.html">${u.name.split(" ")[0]}</a><button onclick="logout()">Logout</button>`:`<a href="login.html">Login</a>`}</div></div>`;updateCount()}
function cart(){return JSON.parse(localStorage.getItem("gw_cart")||"[]")}
function updateCount(){const e=document.getElementById("cartCount");if(e)e.textContent=cart().reduce((s,i)=>s+i.qty,0)}
function addCart(p,size="M"){let c=cart();let x=c.find(i=>i.productId===p._id&&i.size===size);if(x)x.qty++;else c.push({productId:p._id,name:p.name,price:p.price,image:p.image,size,qty:1});localStorage.setItem("gw_cart",JSON.stringify(c));updateCount();alert("Added to cart")}
async function toggleWish(id){if(!token()){location.href="login.html";return}try{await api("/wishlist/toggle",{method:"POST",body:JSON.stringify({productId:id})});alert("Wishlist updated")}catch(e){alert(e.message)}}
function card(p){return `<article class="card"><a href="product.html?id=${p._id}"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.onerror=null;this.src='/assets/blouse-fallback.svg'"></a><div class="card-body"><div class="card-top"><span class="muted">${p.category}</span><button class="heart" onclick="toggleWish('${p._id}')">♡</button></div><a href="product.html?id=${p._id}"><h3>${p.name}</h3></a><p class="muted">⭐ ${p.rating||4.7}</p><p class="price">₹${Number(p.price).toLocaleString("en-IN")}</p><button class="btn" onclick='addCart(${JSON.stringify(p)})'>Add to cart</button></div></article>`}
async function loadShop(){let q=new URLSearchParams();let s=document.getElementById("search")?.value.trim();let cat=document.getElementById("category")?.value;if(s)q.set("search",s);if(cat&&cat!=="All")q.set("category",cat);let max=document.getElementById("maxPrice")?.value;if(max)q.set("maxPrice",max);q.set("sort",document.getElementById("sort")?.value||"newest");try{let d=await api("/products?"+q);document.getElementById("shopGrid").innerHTML=d.products.map(card).join("")||"<p>No products found.</p>"}catch(e){document.getElementById("shopGrid").innerHTML=`<p class="error">${e.message}</p>`}}
async function loadProduct(){let id=new URLSearchParams(location.search).get("id");if(!id)return;try{let p=await api("/products/"+id);document.getElementById("productPage").innerHTML=`<div><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.onerror=null;this.src='/assets/blouse-fallback.svg'"></div><div class="product-info"><p class="muted">${p.category}</p><h1>${p.name}</h1><p class="price">₹${p.price.toLocaleString("en-IN")}</p><p>${p.description||""}</p><p>Size</p><div class="sizes">${["S","M","L","XL"].map(s=>`<button onclick="this.parentNode.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));this.classList.add('selected')" data-size="${s}">${s}</button>`).join("")}</div><button class="btn" onclick='addCart(${JSON.stringify(p)})'>Add to cart</button><button class="btn" onclick="toggleWish('${p._id}')">♡ Wishlist</button></div>`}catch(e){document.getElementById("productPage").innerHTML=`<p class="error">${e.message}</p>`}}
function renderCart(){let c=cart(),box=document.getElementById("cartPage");if(!box)return;if(!c.length){box.innerHTML="<p>Your cart is empty. <a href='shop.html'>Shop now</a></p>";return}let total=c.reduce((s,i)=>s+i.price*i.qty,0);box.innerHTML=c.map((i,n)=>`<div class="cart-row"><img src="${i.image}"><div><h3>${i.name}</h3><p>Size: ${i.size} • ₹${i.price}</p><button onclick="changeQty(${n},-1)">−</button> ${i.qty} <button onclick="changeQty(${n},1)">+</button><button onclick="removeCart(${n})"> Remove</button></div><b>₹${(i.price*i.qty).toLocaleString("en-IN")}</b></div>`).join("")+`<div class="summary"><h2>Total ₹${total.toLocaleString("en-IN")}</h2><a class="btn" href="checkout.html">Checkout</a></div>`}
function changeQty(n,d){let c=cart();c[n].qty+=d;if(c[n].qty<=0)c.splice(n,1);localStorage.setItem("gw_cart",JSON.stringify(c));renderCart();updateCount()}
function removeCart(n){let c=cart();c.splice(n,1);localStorage.setItem("gw_cart",JSON.stringify(c));renderCart();updateCount()}
async function loadWishlist(){let box=document.getElementById("wishlistGrid");if(!box)return;if(!token()){box.innerHTML="<p>Please <a href='login.html'>login</a> to view your wishlist.</p>";return}try{let d=await api("/wishlist");box.innerHTML=d.products.map(card).join("")||"<p>Your wishlist is empty.</p>"}catch(e){box.innerHTML=`<p class="error">${e.message}</p>`}}
async function loginForm(){let f=document.getElementById("loginForm");if(!f)return;f.onsubmit=async e=>{e.preventDefault();try{let d=await api("/auth/login",{method:"POST",body:JSON.stringify({email:email.value,password:password.value})});localStorage.setItem("gw_token",d.token);localStorage.setItem("gw_user",JSON.stringify(d.user));location.href=d.user.role==="admin"?"admin.html":"index.html"}catch(e){msg.textContent=e.message}}}
async function registerForm(){let f=document.getElementById("registerForm");if(!f)return;f.onsubmit=async e=>{e.preventDefault();try{let d=await api("/auth/register",{method:"POST",body:JSON.stringify({name:name.value,email:email.value,password:password.value})});localStorage.setItem("gw_token",d.token);localStorage.setItem("gw_user",JSON.stringify(d.user));location.href="index.html"}catch(e){msg.textContent=e.message}}}
async function checkoutForm(){let f=document.getElementById("checkoutForm");if(!f)return;if(!token()){f.innerHTML="<p>Please login before checkout.</p><a class='btn' href='login.html'>Login</a>";return}f.onsubmit=async e=>{e.preventDefault();let items=cart();if(!items.length){msg.textContent="Your cart is empty";return}try{let d=await api("/orders",{method:"POST",body:JSON.stringify({items,shipping:{name:name.value,phone:phone.value,address:address.value,city:city.value,pincode:pincode.value},paymentMethod:payment.value})});if(payment.value==="RAZORPAY"&&d.razorpay){let r=new Razorpay({key:d.razorpay.key,amount:d.razorpay.amount,currency:"INR",name:"GlowWear",description:"Fashion order",order_id:d.razorpay.orderId,handler:async response=>{await api("/payments/verify",{method:"POST",body:JSON.stringify({...response,orderId:d.orderId})});localStorage.removeItem("gw_cart");location.href="orders.html"},prefill:{name:name.value}});r.open()}else{localStorage.removeItem("gw_cart");msg.className="success";msg.textContent="Order placed successfully";setTimeout(()=>location.href="orders.html",1000)}}catch(e){msg.textContent=e.message}}}
async function loadOrders(){let box=document.getElementById("orders");if(!box)return;if(!token()){box.innerHTML="<p>Please login.</p>";return}try{let d=await api("/orders/my");box.innerHTML=d.orders.map(o=>`<div class="order"><b>#${o._id}</b><p>Status: ${o.status} • Payment: ${o.paymentStatus}</p><p>Total: ₹${o.total.toLocaleString("en-IN")}</p></div>`).join("")||"<p>No orders yet.</p>"}catch(e){box.innerHTML=`<p class="error">${e.message}</p>`}}
document.addEventListener("DOMContentLoaded",async()=>{if(document.getElementById("siteHeader"))header();if(document.getElementById("featured")){try{let d=await api("/products?limit=4");document.getElementById("featured").innerHTML=d.products.map(card).join("")}catch(e){document.getElementById("featured").innerHTML=`<p class="error">${e.message}</p>`}}if(document.getElementById("shopGrid")){let p=new URLSearchParams(location.search);if(p.get("category"))document.getElementById("category").value=p.get("category");loadShop()}loadProduct();renderCart();loadWishlist();loginForm();registerForm();checkoutForm();loadOrders()})